project:
  type: website

website:
  title: "Snow Valormae"
  navbar:
    left:
      # - href: index.qmd
      - text: about
        file: about.qmd
      - text: projects
        file: projects.qmd
      - text: gallery
        file: gallery.qmd
      - text: contact
        file: contact.qmd
    right:
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=100089887522806
      - icon: instagram
        href: https://www.instagram.com/valormae_music

  search: false

format:
  html:
    # theme: cyborg
    theme: lux
    # theme: sketchy
    # theme: vapor
    css: styles.css
    toc: false


execute:
  freeze: auto
