# Terms and Conditions for Guitar Tutoring Services

(@) Lesson Rates:<br>
	•	30-minute lesson: $40<br>
	•	45-minute lesson: $60<br>
	•	60-minute lesson: $80
(@) Invoicing and Payment<br>
	•	Invoices will be issued at the beginning of each school term and will include the total cost of lessons for the term, as well as a one-off cost for learning materials.<br>
	•	Payment is due within 7 days of the invoice date unless a payment plan has been agreed upon.<br>
	•	Payment plans are available upon request and must be arranged before the start of the term.<br>
	•	Holiday Lessons: Additional lessons during school holidays are available and can be paid per lesson or added to the invoice for the adjacent term.
(@) Makeup Lessons and Cancellation Policy<br>
	•	Each student is entitled to one makeup lesson per term. The makeup lesson must be scheduled within the same term.<br>
	•	Makeup lessons must be arranged in accordance with the Cancellation Policy (see below) and are not transferable to subsequent terms.<br>
	•	If a lesson needs to be canceled by the student, a minimum of 24 hours' notice is required. Lessons canceled with less than 24 hours' notice will be charged at the full rate unless otherwise agreed upon.<br>
	•	If the tutor must cancel a lesson, it will be rescheduled at a mutually convenient time or credited towards the next term's invoice.<br>
(@) Sick Policy and Online Lessons<br>
	•	If a student is unable to attend an in-person lesson due to illness, a Zoom or Skype lesson will be offered at the same scheduled time.<br>
	•	The student or parent/guardian must notify the tutor of illness at least 24 hours in advance to qualify for an online lesson.<br>
(@) Learning Materials<br>
	•	Each term's invoice will include a one-off cost for learning materials. This fee covers all materials required for the term.
(@) Liability<br>
	•	The tutor is not liable for any injuries sustained during lessons, either in-person or online. Students are responsible for their own safety and are encouraged to use proper techniques and equipment.
(@) Agreement to Terms<br>
	•	By enrolling in guitar lessons, the student or their parent/guardian agrees to abide by these terms and conditions. The tutor reserves the right to modify these terms at any time, with notice provided to students and parents/guardians.

